plugins {
    id 'com.android.application'
}

android {
    namespace 'com.vhanma.purecombocaller'
    compileSdk 34

    defaultConfig {
        applicationId 'com.vhanma.purecombocaller'
        minSdk 23
        targetSdk 34
        versionCode 1
        versionName '1.0-PureCaller'
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
