package com.vhanma.freqsight;

public enum FilterMode {
    RAW("Raw camera"),
    GRAYSCALE("Grayscale"),
    NEGATIVE("Negative"),
    HIGH_CONTRAST("High contrast"),
    LOCAL_CONTRAST("Local contrast"),
    GAMMA_LOW("Gamma lift"),
    GAMMA_HIGH("Gamma crush"),
    DENOISE("Spatial denoise"),
    UNSHARP("Unsharp detail"),
    SOBEL("Sobel edges"),
    HORIZONTAL_EDGES("Horizontal edges"),
    VERTICAL_EDGES("Vertical edges"),
    LAPLACIAN("Laplacian edges"),
    EMBOSS("Emboss relief"),
    ADAPTIVE_THRESHOLD("Adaptive threshold"),
    BINARY("Binary threshold"),
    DIFFERENCE("Difference map"),
    DIFFERENCE_HEAT("Difference heat"),
    STABLE_DIFFERENCE("Stable difference"),
    FLICKER_MAP("Flicker map"),
    PERSISTENCE_MAP("Persistence map"),
    SMOKE_ENHANCE("Smoke enhancement"),
    VAPOR_DENSITY("Vapor density"),
    SHADOW_ISOLATE("Shadow isolation"),
    SHADOW_GEOMETRY("Shadow geometry"),
    REFLECTION_ISOLATE("Reflection isolation"),
    GLARE_SUPPRESS("Glare suppression"),
    REFRACTION_MAP("Refraction map"),
    MIRROR_SYMMETRY("Mirror symmetry"),
    CONDENSATION("Condensation texture"),
    CHROMA_ANOMALY("Chroma anomaly"),
    RED_CHANNEL("Red channel"),
    GREEN_CHANNEL("Green channel"),
    BLUE_CHANNEL("Blue channel"),
    RGB_SPLIT("RGB split"),
    SATURATION("Saturation view"),
    FALSE_COLOR("False color"),
    LOW_LIGHT("Low-light recovery"),
    TEMPORAL_AVERAGE("Temporal average"),
    MOTION_TRAIL("Motion trails"),
    GLYPH_EDGE("Glyph extraction"),
    GRID_REGIONS("Evidence grid");

    public final String label;
    FilterMode(String label) { this.label = label; }
}