package com.vhanma.hanmacombocallerr3;
import java.util.*;
public class TacticalEngine{
 public static final String[] MODES={"Boxing Only","All Striking","Muay Thai","Kickboxing","MMA","Combat Sambo","Wrestling","No-Gi Grappling","Karate","52 Blocks Boxing","Hybrid Fight Lab","Anime Hybrid (Real Mechanics)","Branching Spar","Adaptive Fight IQ","Pure Library"};
 public static final String[] DISCIPLINES=Arrays.copyOf(MODES,12);
 public static final String[] OPPONENTS={"Adaptive Rival","Pressure Fighter","Counter Striker","Wrestler","Southpaw Sniper","High Guard Shell","Long Kicker","Dirty Boxer","Submission Hunter","Switch Hitter","Cage Wrestler","Blitz Fighter","Attrition Kicker","Scramble Monster","Chaos Rival"};
 public static final String[] PROFILES={"Hanma Adaptive","Ilia Topuria","Prime Conor McGregor","Benny Urquidez","Bas Rutten","Jon Jones","Nick Diaz","Anderson Silva","Justin Gaethje","Sean O'Malley","Georges St-Pierre","Lyoto Machida","Alex Pereira","Demetrious Johnson","Max Holloway","Islam Makhachev","Petr Yan","Miyamoto Musashi","Sun Tzu","52 Blocks Sentinel","Michael Jai White","World Class Boxing"};
 public static final String[] DOCTRINES={"Omega Synthesis","World Class Boxing / Tom Yankello","Muay Thai Guy / Sean Fagan","FIGHTTIPS","Jesse Enkamp / Karate Nerd","MMA Shredded / Jeff Chan","Precision Striking","Punch Doctor Biomechanics","Modern Martial Artist","Trevor Wittman / Gaethje","Benny Urquidez","Michael Jai White","52 Blocks","User Technique Merged Biomechanics","User Combat Master Notes","Baki / Kengan Inspiration"};
 public static class Config{public String mode="MMA",opponent="Adaptive Rival",profile="Hanma Adaptive",doctrine="Omega Synthesis",startRange="Boxing",stance="Orthodox",discipline="";public int difficulty=8,revealDelayMs=1400;}
 public static class Result{public final String opponentEvent,cue,state,why,mind,source,purpose,expectedReply,reaction,ring,shard,doctrine,pattern;public final int windowMs;public Result(String a,String b,String c,String d,String e,String f,String g,String h,String i,String j,String k,String l,String m,int n){opponentEvent=a;cue=b;state=c;why=d;mind=e;source=f;purpose=g;expectedReply=h;reaction=i;ring=j;shard=k;doctrine=l;pattern=m;windowMs=n;}}
 private static class M{String n,f,r,e;Set<String>s;M(String x){String[]p=x.split("\\|");n=p[0];f=p[1];r=p[2];e=p[3];s=new HashSet<>(Arrays.asList(p[4].split(",")));}}
 private static class E{String t,f,r;E(String a,String b,String c){t=a;f=b;r=c;}}
 private final Random q=new Random();private final List<String>named,coded;private final List<M>mv=new ArrayList<>();private final Deque<String>rp=new ArrayDeque<>(),rm=new ArrayDeque<>(),rf=new ArrayDeque<>();private final Map<String,Integer>hab=new LinkedHashMap<>(),ctx=new LinkedHashMap<>(),bel=new LinkedHashMap<>(),crd=new LinkedHashMap<>(),shd=new LinkedHashMap<>();private Config c=new Config();private int pressure=50,streak=0;private String range="Boxing",ring="CENTER",react="UNCERTAIN",pat="UNCERTAIN",shard="SHARD • BUILDING",threat="",plan="";private boolean solved=true;
 public TacticalEngine(List<String>a,List<String>b){named=a==null?Collections.emptyList():a;coded=b==null?Collections.emptyList():b;seed();}
 private void seed(){String[]x={
 "jab|jab|Long|Boxing|B,S,T,K,M,A,R,F,H,N","stiff jab|jab|Boxing|Boxing|B,S,T,K,M,A,F,H,N","body jab|jab|Boxing|Boxing|B,S,T,K,M,A,F,H,N","double jab|jab|Long|Boxing|B,S,T,K,M,A,F,H,N","rear straight|straight|Boxing|Boxing|B,S,T,K,M,A,R,F,H,N","rear straight to body|straight|Boxing|Pocket|B,S,T,K,M,A,F,H,N","lead hook|hook|Pocket|Pocket|B,S,T,K,M,A,F,H,N","lead shovel hook to liver|hook|Pocket|Pocket|B,S,T,K,M,A,F,H,N","rear uppercut|uppercut|Pocket|Pocket|B,S,T,K,M,A,F,H,N","check hook and pivot|hook|Boxing|Long|B,S,T,K,M,A,F,H,N","pull rear straight|straight|Boxing|Boxing|B,S,T,K,M,A,F,H,N","rear-hand parry to power jab|parry|Boxing|Boxing|B,S,M,F,H","lead hand trap to rear straight|trap|Pocket|Pocket|B,S,M,F,H,N","shoulder roll to rear straight|roll|Pocket|Boxing|B,F,H","cross-block to lead hook|block|Pocket|Pocket|B,F,H","split-entry forearm shield to body cross|block|Pocket|Pocket|F,H","forearm shield to pivot hook|block|Pocket|Boxing|F,H",
 "inside low kick|kick|Boxing|Boxing|S,T,K,M,A,H,N","outside calf kick|kick|Long|Long|S,T,K,M,A,H,N","rear body round kick|kick|Long|Long|S,T,K,M,A,R,H,N","lead head kick|kick|Long|Long|S,T,K,M,A,R,H,N","rear head kick|kick|Long|Long|S,T,K,M,A,R,H,N","lead teep|teep|Long|Long|S,T,K,M,A,H","rear teep|teep|Long|Long|S,T,K,M,A,H","lead side kick|sidekick|Long|Long|S,K,M,R,H,N","oblique kick|sidekick|Long|Long|S,M,R,H","switch kick to body|kick|Long|Long|S,T,K,M,H","rear knee from collar tie|knee|Clinch|Clinch|T,M,A,H,N","frame to straight knee|knee|Clinch|Clinch|T,M,A,H","short horizontal elbow|elbow|Clinch|Clinch|T,M,A,H","up elbow off collar tie|elbow|Clinch|Clinch|T,M,A,H","kick catch to outside sweep|sweep|Long|Top|T,M,A,H",
 "blitz reverse punch|straight|Long|Boxing|S,K,M,R,H,N","lead-leg side kick|sidekick|Long|Long|S,K,M,R,H,N","question-mark kick|kick|Long|Long|S,T,K,M,R,H,N","pendulum step reset|footwork|Boxing|Long|B,S,T,K,M,A,R,F,H,N","L-step angle exit|footwork|Boxing|Long|B,S,T,K,M,A,R,F,H,N","V-step outside angle|footwork|Long|Boxing|B,S,K,M,R,H,N",
 "double leg|shot|Boxing|Top|M,A,W,G,H","single leg|shot|Boxing|Top|M,A,W,G,H","knee tap from underhook|shot|Clinch|Top|M,A,W,G,H","body lock mat return|throw|Clinch|Top|M,A,W,G,H","inside trip from over-under|trip|Clinch|Top|M,A,W,G,H","harai-style hip throw from overhook|throw|Clinch|Top|A,M,H,N","whizzer turn to angle|wdef|Clinch|Boxing|M,A,W,G,H","sprawl to front headlock|sprawl|Boxing|Clinch|M,A,W,G,H","crossface and circle off single leg|wdef|Clinch|Boxing|M,A,W,G,H","wall pummel to double underhooks|pummel|Clinch|Clinch|M,A,W,G,H","knee shield hip escape|escape|Ground|Ground|M,A,G,H","technical stand-up from open guard|escape|Ground|Long|M,A,G,H","half-guard underhook to dogfight|escape|Ground|Clinch|M,A,W,G,H","knee-cut pass|pass|Top|Top|M,A,G,H","body-lock pass|pass|Top|Top|M,A,G,H","wrist ride to mat return|ride|Top|Top|M,A,W,G,H","arm triangle setup|submission|Top|Top|M,A,G,H","rear naked choke setup|submission|Top|Top|M,A,G,H","kimura trap to back take|submission|Top|Top|M,A,G,H","straight ankle lock|submission|Ground|Ground|A,G,H",
 "rhythm break shoulder feint to liver hook|anime|Boxing|Pocket|N,H","stance-drop level feint to rising cross|anime|Boxing|Boxing|N,H","step-through cross to rear round kick|anime|Boxing|Long|N,H,M,S"};for(String z:x)mv.add(new M(z));}
 public Config getConfig(){return c;}public void setConfig(Config x){c=x==null?new Config():x;range=nr(c.startRange);streak=0;}public int getRivalPressure(){return pressure;}public String getRingZone(){return ring;}public String getConditionPattern(){return pat;}public String getShardStatus(){return shard;}public String getLastThreat(){return threat;}public boolean lastResponseSolvedThreat(){return solved;}public boolean lastPlanHasLoop(){String[]p=plan.split(" → ");return p.length>2&&p[p.length-1].equalsIgnoreCase(p[p.length-3]);}public int lastPlanMorphCount(){return plan.toLowerCase().contains("feint")?1:0;}
 public String validateKnowledge(){return mv.size()<55?"R8 move graph too small":"";}private String nr(String r){return r==null?"Boxing":Arrays.asList("Long","Boxing","Pocket","Clinch","Ground","Top").contains(r)?r:"Boxing";}
 private String sk(){String m=c.discipline!=null&&!c.discipline.esEmpty()?c.discipline:c.mode,x=m.toLowerCase();if(x.contains("boxing")&&!x.contains("52"))return"B";if(x.contains("52"))return"F";if(x.contains("muay"))return"T";if(x.contains("kickboxing"))return"K";if(x.contains("sambo"))return"A";if(x.contains("wrest"))return"W";if(x.contains("no-gi"))return"G";if(x.contains("karate"))return"R";if(x.contains("anime"))return"N";if(x.contains("striking"))return"S";if(x.contains("mma"))return"M";return"H";}
 private E ev(){String s=sk();List<E>e=new ArrayList<>(Arrays.asList(new E("Opponent probes with a stiff jab","jab","Boxing"),new E("Opponent storms behind a double jab","doubleJab","Boxing"),new E("Opponent drives a rear straight down the center","straight","Boxing"),new E("Opponent crashes in with a lead hook","hook","Pocket"),new E("Opponent digs a rear uppercut in the pocket","uppercut","Pocket")));if(!"BFWG".contains(s)){e.add(new E("Opponent chops an outside low kick","lowKick","Long"));e.add(new E("Opponent whips a rear body kick","bodyKick","Long"));e.add(new E("Opponent fires a head kick","headKick","Long"));e.add(new E("Opponent spears a teep into your center","teep","Long"));}if("TMAHN".contains(s)){e.add(new E("Opponent ties a collar and drives a knee","knee","Clinch"));e.add(new E("Opponent steps in with a short elbow","elbow","Clinch"));}if("MAWGH".contains(s)){e.add(new E("Opponent level changes into a double leg","shot","Boxing"));e.add(new E("Opponent gets to a single leg","single","Clinch"));e.add(new E("Opponent locks a body lock on the fence","bodylock","Clinch"));e.add(new E("Opponent settles heavy top pressure","ground","Ground"));e.add(new E("Opponent takes your back and hunts the neck","back","Ground"));e.add(new E("Opponent isolates your arm for an armbar","armbar","Ground"));e.add(new E("Opponent closes a triangle around your neck and arm","triangle","Ground"));e.add(new E("Opponent wraps a guillotine during the scramble","guillotine","Ground"));}return e.get(q.nextInt(e.size()));}
 private String def(String f){String[]a;if(f.equals("doubleJab